spring.application.name=asset-maintenance

spring.datasource.username=root
spring.datasource.password=
spring.datasource.url=jdbc:mysql://localhost:3306/asset_db

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
