spring.application.name=asset-maintenance

spring.datasource.url=jdbc:postgresql://dpg-d8l90f4vikkc73chfplg-a.singapore-postgres.render.com:5432/mydb_g2nz
spring.datasource.username=postgres1
spring.datasource.password=xhuTlgzyDCZ6guAQe67eOLr6t0qxBquw
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=${PORT:8080}
